Shellism fixes

diff --git a/scripts/gm/bin/lib-gm b/scripts/gm/bin/lib-gm
--- a/scripts/gm/bin/lib-gm
+++ b/scripts/gm/bin/lib-gm
@@ -37,16 +37,16 @@ enforce_requirements() {
 
 debug() {
   if [ -n "${DEBUG:-}" ]; then
-    echo "DEBUG: $@"
+    echo "DEBUG: $*"
   fi
 }
 
 warn() {
-  echo "WARNING: $@"
+  echo "WARNING: $*"
 }
 
 exit_with_error() {
-  echo "ERROR: $@, exiting..."
+  echo "ERROR: $*, exiting..."
   return 1
 }
 
@@ -74,7 +74,7 @@ a_in_b() {
   test -n "$(echo "$2" | grep '\(^\| \+\)'"${1}"'\( \+\|$\)')"
 }
 
-# Todo: (high-prio) fix sconfig so it reads empty sections too
+# Todo: fix "stoml" so it reads empty sections too - currently we work around this with the mandatory comment.
 load_config() {
   FRESH_CONFIG=no
   if [ -f "${SCRIPT_DIR}gm.toml" ]; then
@@ -89,14 +89,18 @@ load_config() {
       export CONFIG_FILE="${SCRIPT_DIR}gm.toml"
     fi
   fi
-  export GLOBAL_GAIAD_BINARY="$(eval echo "$(stoml -q "$CONFIG_FILE" global.gaiad_binary || echo "$(which gaiad)")")"
-  export GLOBAL_PORTS_START_AT="$(stoml -q "$CONFIG_FILE" global.ports_start_at || echo 27000)"
-  export GLOBAL_HOME_DIR="$(eval echo "$(stoml -q "$CONFIG_FILE" global.home_dir || echo "${HOME}/.gm")")"
-  export GLOBAL_AUTO_MAINTAIN_CONFIG="$(stoml -q "$CONFIG_FILE" global.auto_maintain_config || echo "true")"
+  GLOBAL_GAIAD_BINARY="$(eval echo "$(stoml -q "$CONFIG_FILE" global.gaiad_binary || which gaiad)")"
+  GLOBAL_PORTS_START_AT="$(stoml -q "$CONFIG_FILE" global.ports_start_at || echo 27000)"
+  GLOBAL_HOME_DIR="$(eval echo "$(stoml -q "$CONFIG_FILE" global.home_dir || echo "${HOME}/.gm")")"
+  GLOBAL_AUTO_MAINTAIN_CONFIG="$(stoml -q "$CONFIG_FILE" global.auto_maintain_config || echo "true")"
+  export GLOBAL_GAIAD_BINARY
+  export GLOBAL_PORTS_START_AT
+  export GLOBAL_HOME_DIR
+  export GLOBAL_AUTO_MAINTAIN_CONFIG
   if [ "$FRESH_CONFIG" = "yes" ]; then
     write_default_config
-    export VALIDATORS=""
-    export FULL_NODES=""
+    VALIDATORS=""
+    FULL_NODES=""
   else
     stoml "$CONFIG_FILE" global 1> /dev/null || exit_with_error invalid config file. Make sure all strings are quoted
     test -x "$GLOBAL_GAIAD_BINARY" || exit_with_error "gaiad binary cannot be executed: $GLOBAL_GAIAD_BINARY"
@@ -108,7 +112,7 @@ load_config() {
       if [ "$i" = "global" ]; then
         continue
       fi
-      if [ -z "$(stoml "$CONFIG_FILE" ${i}.network)" ]; then
+      if [ -z "$(stoml "$CONFIG_FILE" "${i}.network")" ]; then
         VALIDATORS="$VALIDATORS $i"
       else
         RAW_NODES="$RAW_NODES $i"
@@ -117,16 +121,16 @@ load_config() {
     FULL_NODES=""
     for i in $RAW_NODES
     do
-      NODE_NETWORK="$(stoml "$CONFIG_FILE" ${i}.network)"
+      NODE_NETWORK="$(stoml "$CONFIG_FILE" "${i}.network")"
       if ! a_in_b "${NODE_NETWORK}" "$VALIDATORS"; then
         warn "invalid full node: $i, invalid network entry: ${NODE_NETWORK}, skipping..."
         continue
       fi
       FULL_NODES="${FULL_NODES} $i"
     done
-    export VALIDATORS
-    export FULL_NODES
   fi
+  export VALIDATORS
+  export FULL_NODES
   export ALL_NODES="$VALIDATORS $FULL_NODES"
 }
 
@@ -138,21 +142,22 @@ gaiad_binary="$GLOBAL_GAIAD_BINARY"
 ports_start_at=$GLOBAL_PORTS_START_AT
 home_dir="$GLOBAL_HOME_DIR"
 auto_maintain_config=$GLOBAL_AUTO_MAINTAIN_CONFIG
+comment="Please add comments to all node definitions. (Mandatory.)"
 EOF
   set -e
 }
 
 get_gaiad_binary() {
-  RESULT="$(stoml -q "$CONFIG_FILE" ${1}.gaiad_binary)"
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.gaiad_binary")"
   if [ -z "$RESULT" ]; then
     echo "$GLOBAL_GAIAD_BINARY"
   else
-    echo "$(eval echo "$RESULT")"
+    eval echo "$RESULT"
   fi
 }
 
 get_ports_start_at() {
-  RESULT="$(stoml -q "$CONFIG_FILE" ${1}.ports_start_at)"
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.ports_start_at")"
   if [ -z "$RESULT" ]; then
     i=0
     for j in $ALL_NODES
@@ -169,7 +174,7 @@ get_ports_start_at() {
 }
 
 get_rpc_port() {
-  echo "$(get_ports_start_at "$1")"
+  get_ports_start_at "$1"
 }
 
 get_app_port() {
@@ -189,16 +194,16 @@ get_pprof_port() {
 }
 
 get_home_dir() {
-  RESULT="$(stoml -q "$CONFIG_FILE" ${1}.home_dir)"
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.home_dir")"
   if [ -z "$RESULT" ]; then
     echo "$GLOBAL_HOME_DIR/$1"
   else
-    echo "$(eval echo "$RESULT")"
+    eval echo "$RESULT"
   fi
 }
 
 get_auto_maintain_config() {
-  RESULT="$(stoml -q "$CONFIG_FILE" ${1}.auto_maintain_config)"
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.auto_maintain_config")"
   if [ -z "$RESULT" ]; then
     test "$GLOBAL_AUTO_MAINTAIN_CONFIG" = "true"
   else
@@ -207,7 +212,7 @@ get_auto_maintain_config() {
 }
 
 get_network() {
-  RESULT="$(stoml -q "$CONFIG_FILE" ${1}.network)"
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.network")"
   if [ -z "$RESULT" ]; then
     exit_on_error "Network not found for node ${1}"
   else
@@ -271,8 +276,8 @@ configure() {
   # Todo: rpc.grpc also?
   P2P="$(get_p2p_port "$1")"
   RPC="$(get_rpc_port "$1")"
-  APP="$(get_app_port "$1")"
-  GRPC="$(get_grpc_port "$1")"
+  #APP="$(get_app_port "$1")"
+  #GRPC="$(get_grpc_port "$1")"
   PPROF="$(get_pprof_port "$1")"
   sconfig "$HOME_DIR/config/config.toml" "p2p.laddr=tcp://0.0.0.0:${P2P}" 1> /dev/null
   sconfig "$HOME_DIR/config/config.toml" "rpc.laddr=tcp://0.0.0.0:${RPC}" 1> /dev/null
@@ -289,17 +294,17 @@ configure() {
     if get_auto_maintain_config "$NETWORK"; then
       NODE_ID="$(get_node_id "$1")"
       sconfig "$NETWORK_HOME_DIR/config/config.toml" "p2p.unconditional_peer_ids=$NODE_ID" 1> /dev/null
-      # Todo: Make this more robust: if two full nodes connect to the same validator, this override each other
+      # Todo: Make this more robust: if two full nodes connect to the same validator, don't override each other
     fi
   fi
 }
 
-# Todo: (high-prio) fix sconfig to be able to map in app.toml
+# Todo: (high-priority) fix sconfig to be able to map in app.toml
 start() {
   GAIAD="$(get_gaiad_binary "$1")"
   HOME_DIR="$(get_home_dir "$1")"
   GAIAD_LOG="${HOME_DIR}/log"
-  nohup $GAIAD start --x-crisis-skip-assert-invariants --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 &
+  nohup "$GAIAD" start --x-crisis-skip-assert-invariants --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 &
   GAIAD_PID=$!
   echo "$GAIAD_PID" > "$HOME_DIR/pid"
   echo "$i started, PID: $GAIAD_PID, LOG: $GAIAD_LOG"
@@ -307,7 +312,7 @@ start() {
 
 stop() {
   HOME_DIR="$(get_home_dir "$1")"
-  GAIAD_BINARY="$(get_gaiad_binary "$1")"
+  #GAIAD_BINARY="$(get_gaiad_binary "$1")"
   test -f "${HOME_DIR}/pid"
   GAIAD_PID="$(cat "${HOME_DIR}/pid")"
   #COMM="$(ps -p "$GAIAD_PID" -o comm | tail -1)"
@@ -328,7 +333,7 @@ print_status_line() {
     GAIAD_PID_FILE="${HOME_DIR}/pid"
     if [ -f "$GAIAD_PID_FILE" ]; then
       GAIAD_PID="$(cat "$GAIAD_PID_FILE")"
-      if [ $(ps -p "$GAIAD_PID" -o pid | wc -l) -eq 2 ]; then
+      if [ "$(ps -p "$GAIAD_PID" -o pid | wc -l)" -eq 2 ]; then
         echo "$I$1  $GAIAD_PID  $(get_rpc_port "$1") $(get_app_port "$1") $(get_grpc_port "$1") $HOME_DIR"
       else
         echo "$I$1 ($GAIAD_PID)     -     -     - $HOME_DIR"
