Added rm command, renamed reset command, added wallet_mnemonics config param

diff --git a/scripts/gm/bin/lib-gm b/scripts/gm/bin/lib-gm
--- a/scripts/gm/bin/lib-gm
+++ b/scripts/gm/bin/lib-gm
@@ -16,6 +16,7 @@ config_defaults() {
     GLOBAL_HERMES_CONFIG="${HOME}/.hermes/config.toml"
     GLOBAL_AUTO_MAINTAIN_CONFIG="true"
     GLOBAL_ADD_TO_HERMES="false"
+    GLOBAL_WALLET_MNEMONIC=""
 }
 
 install() {
@@ -133,6 +134,27 @@ n_from_a() {
   return 1
 }
 
+# Todo: do we want to use this?
+is_configuration_valid() {
+  if ! a_in_b "$1" "$ALL_NODES"; then
+    return 1
+  fi
+  HOME_DIR="$(get_home_dir "$1")"
+  for d in "$HOME_DIR" "${HOME_DIR}/config" "${HOME_DIR}/data"
+  do
+    if [ ! -d "$d" ]; then
+      return 1
+    fi
+  done
+  for f in "${HOME_DIR}/config/config.toml" "${HOME_DIR}/config/app.toml" "${HOME_DIR}/config/node_key.json"
+  do
+    if [ ! -f "$f" ]; then
+      return 1
+    fi
+  done
+  return 0
+}
+
 load_all_sections() {
   grep '^ *\[.\+\] *$' "$CONFIG_FILE" | sed 's/^ *\[\([^]]*\)\] *$/\1/'
 }
@@ -158,12 +180,14 @@ load_config() {
   GLOBAL_HERMES_CONFIG="$(eval echo "$(stoml -q "$CONFIG_FILE" global.hermes_config || echo "$GLOBAL_HERMES_CONFIG")")"
   GLOBAL_AUTO_MAINTAIN_CONFIG="$(stoml -q "$CONFIG_FILE" global.auto_maintain_config || echo "$GLOBAL_AUTO_MAINTAIN_CONFIG")"
   GLOBAL_ADD_TO_HERMES="$(stoml -q "$CONFIG_FILE" global.add_to_hermes || echo "$GLOBAL_ADD_TO_HERMES")"
+  GLOBAL_WALLET_MNEMONIC="$(stoml -q "$CONFIG_FILE" global.wallet_mnemonic || echo "$GLOBAL_WALLET_MNEMONIC")"
   export GLOBAL_GAIAD_BINARY
   export GLOBAL_HERMES_BINARY
   export GLOBAL_HOME_DIR
   export GLOBAL_HERMES_CONFIG
   export GLOBAL_AUTO_MAINTAIN_CONFIG
   export GLOBAL_ADD_TO_HERMES
+  export GLOBAL_WALLET_MNEMONIC
   if [ "$FRESH_CONFIG" = "yes" ]; then
     write_default_config
     VALIDATORS=""
@@ -236,6 +260,7 @@ auto_maintain_config=$GLOBAL_AUTO_MAINTAIN_CONFIG
 add_to_hermes=$GLOBAL_ADD_TO_HERMES
 hermes_binary="$GLOBAL_HERMES_BINARY"
 hermes_config="$GLOBAL_HERMES_CONFIG"
+wallet_mnemonic="$GLOBAL_WALLET_MNEMONIC"
 EOF
   set -e
 }
@@ -331,31 +356,52 @@ get_add_to_hermes() {
 }
 
 get_node_id() {
-  GAIAD="$(get_gaiad_binary "$1")"
+  GAIAD_BINARY="$(get_gaiad_binary "$1")"
   HOME_DIR="$(get_home_dir "$1")"
-  $GAIAD tendermint show-node-id --home "$HOME_DIR"
+  # Todo: Shall we change this to is_configuration_valid?
+  if [ ! -f "${HOME_DIR}/config/node_key.json" ]; then
+    warn "Invalid configuration: no node key found for $1"
+    echo "DEADBEEFDEADBEEF"
+  else
+    "$GAIAD_BINARY" tendermint show-node-id --home "$HOME_DIR"
+  fi
+}
+
+get_wallet_mnemonic() {
+  RESULT="$(stoml -q "$CONFIG_FILE" "${1}.wallet_mnemonic")"
+  if [ -z "$RESULT" ]; then
+    echo "$GLOBAL_WALLET_MNEMONIC"
+  else
+    echo "$RESULT"
+  fi
 }
 
 create() {
   i="$1"
   echo "Creating $i config..."
-  GAIAD="$(get_gaiad_binary "$i")"
+  GAIAD_BINARY="$(get_gaiad_binary "$i")"
   HOME_DIR="$(get_home_dir "$i")"
   HOME_ROOT="${HOME_DIR%%${i}}"
   if a_in_b "$i" "$VALIDATORS"; then
-    EXEC_RESULT="$("$GAIAD" testnet --chain-id "$i" --keyring-backend test --node-dir-prefix "${i}v" -o "$HOME_ROOT" --node-daemon-home . --v 1 2>&1)"
+    EXEC_RESULT="$("$GAIAD_BINARY" testnet --chain-id "$i" --keyring-backend test --node-dir-prefix "${i}v" -o "$HOME_ROOT" --node-daemon-home . --v 1 2>&1)"
     if [ "$EXEC_RESULT" != "Successfully initialized 1 node directories" ]; then
       warn "could not create config for ${i}: \"$EXEC_RESULT\", skipping..."
       return 1
     else
       mv "${HOME_ROOT}/${i}v0" "${HOME_DIR}"
       mv "${HOME_ROOT}/gentxs" "${HOME_DIR}"
-      $GAIAD keys add "wallet" --keyring-backend test --keyring-dir "${HOME_DIR}" --output json > "${HOME_DIR}/wallet_seed.json"
-      $GAIAD add-genesis-account "wallet" "10000000stake,10000localcoin" --keyring-backend test --home "${HOME_DIR}"
+      WALLET_MNEMONIC="$(get_wallet_mnemonic "$i")"
+      if [ -z "$WALLET_MNEMONIC" ]; then
+        "$GAIAD_BINARY" keys add "wallet" --keyring-backend test --keyring-dir "${HOME_DIR}" --output json > "${HOME_DIR}/wallet_seed.json"
+      else
+        echo "$WALLET_MNEMONIC" | "$GAIAD_BINARY" keys add "wallet" --recover --keyring-backend test --keyring-dir "${HOME_DIR}" --output json > "${HOME_DIR}/wallet_seed.json"
+        sconfig "${HOME_DIR}/wallet_seed.json" -t string "mnemonic=${WALLET_MNEMONIC}"
+      fi
+      "$GAIAD_BINARY" add-genesis-account "wallet" "10000000stake,10000localcoin" --keyring-backend test --home "${HOME_DIR}"
     fi
   else
     NETWORK="$(get_network "$i")"
-    EXEC_RESULT="$("$GAIAD" testnet --chain-id "$NETWORK" --keyring-backend test --node-dir-prefix "${i}n" -o "$HOME_ROOT" --node-daemon-home . --v 1 2>&1)"
+    EXEC_RESULT="$("$GAIAD_BINARY" testnet --chain-id "$NETWORK" --keyring-backend test --node-dir-prefix "${i}n" -o "$HOME_ROOT" --node-daemon-home . --v 1 2>&1)"
     if [ "$EXEC_RESULT" != "Successfully initialized 1 node directories" ]; then
       warn "could not create config for ${i}: \"$EXEC_RESULT\", skipping..."
       return 1
@@ -430,15 +476,15 @@ start() {
   if is_running "$1"; then
     warn "$1 is already running, skipping"
   else
-    GAIAD="$(get_gaiad_binary "$1")"
+    GAIAD_BINARY="$(get_gaiad_binary "$1")"
     HOME_DIR="$(get_home_dir "$1")"
     GAIAD_LOG="${HOME_DIR}/log"
-    VALIDATION="$("$GAIAD" validate-genesis --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 || echo "ERR")"
+    VALIDATION="$("$GAIAD_BINARY" validate-genesis --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 || echo "ERR")"
     if [ "$VALIDATION" = "ERR" ]; then
       warn "invalid genesis.json for ${1}. Please check the log and fix manually. Skipping..."
       return 0
     fi
-    nohup "$GAIAD" start --x-crisis-skip-assert-invariants --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 &
+    nohup "$GAIAD_BINARY" start --x-crisis-skip-assert-invariants --home "$HOME_DIR" > "$GAIAD_LOG" 2>&1 &
     GAIAD_PID=$!
     echo "$GAIAD_PID" > "$HOME_DIR/pid"
     echo "$i started, PID: $GAIAD_PID, LOG: $GAIAD_LOG"
@@ -479,7 +525,7 @@ stop() {
 }
 
 print_header_line() {
-  echo "NODE               PID    RPC   APP  GRPC HOME_DIR"
+  echo "NODE               PID    RPC   APP  GRPC  HOME_DIR"
 }
 
 print_status_line() {
@@ -493,6 +539,10 @@ print_status_line() {
       done
     fi
     HOME_DIR="$(get_home_dir "$1")"
+    HOME_DIR_PRINTED=" $HOME_DIR "
+    if [ ! -d "$HOME_DIR" ]; then
+      HOME_DIR_PRINTED="(${HOME_DIR})"
+    fi
     GAIAD_PID_FILE="${HOME_DIR}/pid"
     if [ -f "$GAIAD_PID_FILE" ]; then
       GAIAD_PID="$(cat "$GAIAD_PID_FILE")"
@@ -500,12 +550,12 @@ print_status_line() {
         GAIAD_PID=" N/A "
       fi
       if [ "$(ps -p "$GAIAD_PID" -o pid | wc -l)" -eq 2 ]; then
-        echo "${NAME}${NAME_PAD} $GAIAD_PID  $(get_rpc_port "$1") $(get_app_port "$1") $(get_grpc_port "$1") $HOME_DIR"
+        echo "${NAME}${NAME_PAD} $GAIAD_PID  $(get_rpc_port "$1") $(get_app_port "$1") $(get_grpc_port "$1") $HOME_DIR_PRINTED"
       else
-        echo "${NAME}${NAME_PAD}($GAIAD_PID)     -     -     - $HOME_DIR"
+        echo "${NAME}${NAME_PAD}($GAIAD_PID)     -     -     - $HOME_DIR_PRINTED"
       fi
     else
-       echo "${NAME}${NAME_PAD}     -      -     -     - $HOME_DIR"
+       echo "${NAME}${NAME_PAD}     -      -     -     - $HOME_DIR_PRINTED"
     fi
 }
 
@@ -541,6 +591,11 @@ ports() {
 
 list_keys() {
   HOME_DIR="$(get_home_dir "$1")"
+  # Todo: Should we change this to is_configuration_valid?
+  if [ ! -d "$HOME_DIR" ]; then
+    warn "No configuration at ${HOME_DIR}. Skipping..."
+    return 0
+  fi
   GAIAD_BINARY="$(get_gaiad_binary "$1")"
   echo "\"$GAIAD_BINARY\" keys list --keyring-backend test --keyring-dir \"$HOME_DIR\""
   KEY_NAME=""
@@ -642,7 +697,7 @@ hermes_cc() {
     fi
   done
   CHAINS="${CHAINS## }"
-  N="$(($(wc -w <<< "$CHAINS")))"
+  N="$(($(echo "$CHAINS" | wc -w)))"
   for i in $(seq 1 $((N-1)))
   do
     for j in $(seq $((i+1)) $N)
@@ -652,13 +707,55 @@ hermes_cc() {
   done
 }
 
-unsafe_reset() {
-  if is_running "$1"; then
-    warn "$1 is already running, skipping"
+reset() {
+  WAS_RUNNING="$(is_running "$1" || echo "no")"
+  if [ -z "$WAS_RUNNING" ]; then
+    if a_in_b "$1" "$VALIDATORS"; then
+      warn "After reset all full nodes will need to be reset too."
+    fi
+    stop "$1"
+  fi
+  GAIAD_BINARY="$(get_gaiad_binary "$1")"
+  HOME_DIR="$(get_home_dir "$1")"
+  echo "Resetting $1..."
+  # Todo: Should we change this to is_configuration_valid?
+  if [ ! -d "$HOME_DIR" ]; then
+    warn "No configuration at ${HOME_DIR}. Skipping..."
+    return 0
+  fi
+  "$GAIAD_BINARY" unsafe-reset-all --home "$HOME_DIR"
+  if [ -z "$WAS_RUNNING" ]; then
+    start "$1"
+  fi
+}
+
+# Guard against removing arbitrary folders/files, only remove folders that have at least a half-baked node configuration.
+safer_rm() {
+  if [ $# -eq 1 ]; then
+    if a_in_b "$1" "$ALL_NODES"; then
+      HOME_DIR="$(get_home_dir "$1")"
+      if [ -d "$HOME_DIR" ]; then
+        if [ -d "$HOME_DIR/config" ]; then
+          if [ -f "$HOME_DIR/config/config.toml" ]; then
+            if [ -d "$HOME_DIR/data" ]; then
+              echo "Executing \"rm -r $HOME_DIR\"..."
+              rm -r "$HOME_DIR"
+            else
+              warn "Anxious to run \"rm -r ${HOME_DIR}\" automatically, folder does not contain data folder, skipping..."
+            fi
+          else
+            warn "Anxious to run \"rm -r ${HOME_DIR}\" automatically, folder does not contain config file, skipping..."
+          fi
+        else
+          warn "Anxious to run \"rm -r ${HOME_DIR}\" automatically, folder does not contain config folder, skipping..."
+        fi
+      else
+        warn "Anxious to run \"rm -r ${HOME_DIR}\" automatically, folder does not exist, skipping..."
+      fi
+    else
+      warn "Anxious to delete \"${1}\" automatically, node not in configuration, skipping..."
+    fi
   else
-    GAIAD="$(get_gaiad_binary "$1")"
-    HOME_DIR="$(get_home_dir "$1")"
-    echo "Resetting $1..."
-    "$GAIAD" unsafe-reset-all --home "$HOME_DIR"
+    warn "Anxious to delete \"${*}\" automatically, looks like multiple paths, skipping..."
   fi
 }
